### ISSUE TITLE
Usage of Elastic causes Cassandra mismatches (read repairs)

### ISSUE THREAD

**Issue by nvidgren** [Axway-API-Management-Plus/apigateway-openlogging-elk#180]
**Axway APIM-ELK version** 
4.1.0

**API-Manager Version** 
7.7 august update

**Question**
Starting the Elastic cluster and Filebeats is causing the API GW Cassandra database to experience considerable amount of mismatches and read repairs (readrepairrepairedblocking). Is this phenomenon known and what could cause it?

**What I've tried so far**
The first idea was to reduce the calls API Builder does towards API GW by enabling the lookup cache with TTL 30 minutes. Then APM was enabled to see if something comes up in its monitoring. 
This did not work and so tracing was enabled in Cassandra but even trace logs are not revealing any information that could be of use to analyze the root cause

**Additional information**
We are running a standard ELK cluster on 4 nodes. API Builder/Logstash is currently running only on one. Filebeats are installed on 6 API GW nodes but the issue occurs already when only one is started. If no Filebeats are running the mismatches are not occurring. 
The ELK configuration is standard apart from the settings described above. Filebeats are stand-alone installations but the Axway configuration file is being used.

The issue only occurs in production where the amount of traffic is considerably more than in our integration environment. In our INT we cannot reproduce the issue.

**Comment by cwiechmann** [comment]
Thanks @nvidgren for reaching out to us. No, the issue is not known to us. Of course, the solution should have no impact on the API-Manager Cassandra-DB. 

A few questions:
- with mismatches, you really man a query against the C* DB without a match?
- how many APIs do you have in your catalog?
  - with APIs I mean the API itself, not the individual operations
- how many Applications do you have in your catalog?
- can you please share the ap. number of requests you have in a 5-10 minutes time window?
  - I'm interested in the peak value you have at a typical day
- any idea why APM was not showing anything?
  - that would help us to see, if API-Lookup-Information is successfully cached or not

This is the expected behavior based on the caching in place. No Lookups in about 10 minutes:
![image](https://user-images.githubusercontent.com/16292002/156515386-bc85a87f-addb-473b-a1cb-f82a2462085c.png)

In a real production environment, this might look a bit different, as API requests and applications are processed with a larger variance. Nevertheless, after a little bit of a warm-up phase, the requests should decrease significantly.

**Comment by nvidgren** [comment]
Hello Chris,

Thanks for the point about ignoring older logs. While this does decrease the load a bit it has not solved our issue with numerous and constant Cassandra read repairs. For the test we let the infrastructure run normally over the weekend and the read repairs occur constantly without any pause.

**Comment by cwiechmann** [comment]
Thanks for the update @nvidgren. I'm running out of ideas, why the solution, when running normally, should create a significant impact on the API-Management Cassandra-DB. Do you have time for a Web-Session? Perhaps, I can see what's going on and may cause this.

You can contact me directly via cwiechmann(at)axway.com

**Comment by nvidgren** [comment]
Hi Chris, sure we can have a web session (including Lucas who submitted issue 192 and who is working on this topic as well).
