### ISSUE TITLE
Mulitple instances in a group cannot view Payloads

### ISSUE THREAD

**Issue by bosa-cihan** [Axway-API-Management-Plus/apigateway-openlogging-elk#233]
### ELK-Solution version

4.5.0

### Elastic-Stack version

7.17.0

### API-Management version

7.7.20220530

### Number of APIs

200

### Number of Applications

3

### Number of Transactions

50000

### API-Management deployment option

Classic VMs

### ELK-Solution deployment option

Classic VMs using Docker-Compose

### Bug description

It is not possible to view payloads if there are multiple instances in a group. Since we share payload folders on each Axway server via NFS share, we have to map them to separate folders in the API Builder container configuration.

![image](https://user-images.githubusercontent.com/87135296/206214101-b1a39440-525c-42f8-80e9-daf66161e694.png)

![image](https://user-images.githubusercontent.com/87135296/206215174-da06139b-4de6-4749-a341-a09a767dd9ca.png)

![image](https://user-images.githubusercontent.com/87135296/206215357-11d29915-2f6b-409c-b7c2-8a9019a76ee3.png)

We need API Builder to look into a dedicated folder for each instance in the /var/log/payloads/ folder similar to the REGIONs.

![image](https://user-images.githubusercontent.com/87135296/206215558-f13b72ec-c4a2-49c5-93c3-28b01d17367b.png)

**Comment by NComandini** [comment]
Payload isn't visible in here but in the popup when you click on "show".
Not sure to understand why 2 differents NFS are required in VM and it's not possible to do a similar solution with an orchestrator because all instances has the same configuration.

Please use the official channel to solve your issue. We will have more tools to investigate your issue.
