### ISSUE TITLE
Add support to checkbox "Reload trace with payload records"

### ISSUE THREAD

**Issue by remisbaima** [Axway-API-Management-Plus/apigateway-openlogging-elk#43]
**User story**
This is a nice to have/low-prio: make the checkbox work.
![image](https://user-images.githubusercontent.com/1174143/93986734-fbca3700-fd86-11ea-9b44-9772dd311b7b.png)

**Additional context**

**Comment by cwiechmann** [comment]
Thanks for raising this request @remisbaima. I had a chat with @rekies about this requirement and we came to the conclusion, that the ELK based Traffic-Monitor cannot support this toggle. 
The reason is, that the Traffic-Trace information is taken from the API-Gateway Trace-Files and those don't contain the Sent- or Received-Data. Furthermore, even if the information is available in the Traffic-Details index, the order, when to show that information, is not known.

And the information, which data is sent and received is already shown as part of the Legs-Blocks.

With that, I'm going to close this issue now. If this isn't acceptable for you, please feel free to re-open this issue.
